localisation: "en"

# Set the radius of local chat.
radius: 200

# If the player should pay to use global chat
global-pay:
  item:
    enabled: false
    material: "REDSTONE"
    amount: 1
  vault:
    enabled: false
    amount: 10

# Both fully support PlaceholderAPI
# Global chat format
global-format: "&8[&cG&8]&r &6%player% &e>&r %message%"

# Local chat format
local-format: "&8[&aL&8]&r &6%player% &e>&r %message%"

mentions:
  enabled: true
  highlight:
    enabled: true
    format: "&e%player%&r"
  sound:
    enabled: true
    name: BLOCK_NOTE_BLOCK_PLING
    volume: 0.7
    pitch: 1.0
  actionbar:
    enabled: true

# Message on player join/leave
join: false

quit: false