name: Chatullo
version: '${project.version}'
main: ua.mykolamurza.chatullo.Chatullo
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  chatullo:
    description: used to reload configuration